template_system = "./system.tmpl"
template_user = "./user.tmpl"
max_tokens = 1000
model = "gpt-3.5-turbo-0613"
temperature = 0.001
presence_penalty = 0.1
frequency_penalty = 0.1

[[functions]]
	name = "insert"
	description = "Insert new threats in the database"
	parameters = '''
{
  "type": "object",
  "required": [
    "id",
    "name",
    "reason",
    "insert"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "The threat ID."
    },
    "name": {
      "type": "string",
      "description": "The name of the threat."
    },
    "reason": {
      "type": "string",
      "description": "Why the threat must be added."
    },
    "insert": {
      "type": "boolean",
      "description": "Whether or not the threat should be inserted."
    }
  }
}
'''