max_tokens = 2000
model = "gpt-4o"
template_system = "./system.tmpl"
temperature = 0.2
top_p = 0.3 
presence_penalty = 0 
frequency_penalty = 0 


[[template_prompt]] 
	role = "user"
	template = "./1shotuser.tmpl"

[[template_prompt]] 
	role = "assistant"
	template = "./1shotassistant.tmpl"

[[template_prompt]] 
	role = "user"
	template = "./user.tmpl"